---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: cloud-config
spec:
  package: ghcr.io/stuttgart-things/crossplane/cloud-config:v0.5.1
---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: volume-claim
spec:
  package: ghcr.io/stuttgart-things/crossplane/volume-claim:v0.1.1
---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: storage-platform
spec:
  package: ghcr.io/stuttgart-things/crossplane/storage-platform:v0.6.0
---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: ansible-run
spec:
  package: ghcr.io/stuttgart-things/crossplane/ansible-run:v12.0.0
---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: pipeline-integration
spec:
  package: ghcr.io/stuttgart-things/crossplane/pipeline-integration:v0.1.2
---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: harvester-vm
spec:
  package: ghcr.io/stuttgart-things/crossplane/harvester-vm:v0.3.3
