---
releases:
  - name: cilium
    installed: true
    namespace: kube-system
    chart: cilium/cilium
    version: 1.17.2
    values:
      - "values/cilium-{{ .Values.config }}.values.yaml.gotmpl"

  - name: cilium-configuration
    disableValidationOnInstall: true
    needs:
      - kube-system/cilium
    installed: {{ .Values.configureLB }}
    namespace: kube-system
    chart: stuttgart-things/sthings-cluster
    version: 0.3.15
    values:
      - "values/cilium-{{ .Values.config }}-config.values.yaml.gotmpl"

repositories:
  - name: cilium
    url: https://helm.cilium.io
    oci: false
  - name: stuttgart-things
    url: eu.gcr.io/stuttgart-things
    oci: true
