---
releases:
  - name: ingress-nginx
    disableValidationOnInstall: true
    installed: true
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: {{ .Values.version }}
    values:
      - "values/ingress-nginx.values.yaml.gotmpl"

repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
    oci: false
