---
releases:
  - name: metrics-server
    installed: true
    namespace: kube-system
    chart: metrics-server/metrics-server
    version: 3.12.2
    values:
      - "values/metrics-server.values.yaml.gotmpl"

repositories:
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server
    oci: false
