---
releases:
  - name: openebs
    installed: true
    namespace: {{ .Values.namespace }}
    chart: openebs/openebs
    version: 4.2.0
    values:
      - "values/openebs-{{ .Values.profile }}.values.yaml.gotmpl"

repositories:
  - name: openebs
    url: https://openebs.github.io/openebs
    oci: false
