---
releases:
  - name: velero
    installed: true
    namespace: {{ .Values.namespace }}
    chart: velero/velero
    version: 8.6.0
    values:
      - "values/velero.values.yaml.gotmpl"

repositories:
  - name: velero
    url: https://vmware-tanzu.github.io/helm-charts/
    oci: false
