---
releases:
  - name: velero
    installed: true
    namespace: velero
    chart: velero/velero
    version: 8.6.0
    values:
      - "values/velero-{{ .Values.profile }}.values.yaml.gotmpl"

repositories:
  - name: velero
    url: https://vmware-tanzu.github.io/helm-charts/
    oci: false
